migrate posts end points with jwt
TheChance101/Cup-Cake-Media-Server pull request #12
Opened 2023-06-15 16:27 UTC by Karrar-Mohammed

as in title

2023-06-16 15:47 UTC, AmeerAmjed commented on src/main/kotlin/com/the_chance/controllers/PostsController.kt
> +            val creatorUUID = isValidUUID(creatorId)
why check validation uuidCreate you already get from token its safe place

2023-06-16 15:58 UTC, AmeerAmjed requested changes
good work, need change some point.

2023-06-16 15:58 UTC, AmeerAmjed commented on src/main/kotlin/com/the_chance/data/post/Post.kt
> +    val creatorName: String
why just creatorName in post class why should provide object user, in design need name and jobTitle and avatar will need object user when need update or delete this post how check is owner post name not unique

2023-06-16 15:58 UTC, AmeerAmjed commented on src/main/kotlin/com/the_chance/data/post/PostService.kt
> +            (PostTable innerJoin UserTable)
you already here create innerJoin to get info user why use just name need return object user.

2023-06-17 19:36 UTC, AmeerAmjed approved these changes

2023-06-17 19:51 UTC, mustafa-sab3alarab approved these changes

2023-06-18 09:37 UTC, merged